"""Structured Pydantic schemas passed between agents with strict typing."""
from typing import List, Literal
from pydantic import BaseModel, Field


class Plan(BaseModel):
    """Generated by Coordinator: defines study trajectory or asks clarification."""
    topic: str = Field(default="", description="The specific subject or concept to teach")
    level: str = Field(default="beginner", description="beginner, intermediate, or advanced")
    needs_clarification: bool = Field(default=False, description="True if the user's intent is ambiguous")
    clarifying_question: str = Field(default="", description="Question asked to student if clarification needed")
    focus_points: List[str] = Field(default_factory=list, description="2-4 core sub-topics to cover")


class Question(BaseModel):
    """Individual assessment item created by Quiz Master."""
    id: int = Field(..., description="1-indexed question ID")
    question: str = Field(..., description="The quiz question text")
    type: Literal["mcq", "short"] = Field(default="mcq", description="mcq or short answer")
    options: List[str] = Field(default_factory=list, description="4 multiple-choice options (e.g. ['A) ...', 'B) ...'])")
    answer_key: str = Field(..., description="Expected correct answer and brief rationale")
    concept: str = Field(..., description="Short tag of the sub-concept being tested")


class Quiz(BaseModel):
    """Structured collection of questions emitted by Quiz Master."""
    title: str = Field(default="Topic Assessment", description="Title of the quiz")
    questions: List[Question] = Field(..., description="List of questions")


class Grade(BaseModel):
    """Grading breakdown per question produced by Evaluator."""
    question_id: int = Field(..., description="ID of question being graded")
    score: int = Field(ge=0, le=2, description="0 (incorrect), 1 (partially correct), 2 (fully correct)")
    feedback: str = Field(..., description="Specific feedback explaining what was right or wrong")
    concept: str = Field(..., description="The concept tag from the question")


class Evaluation(BaseModel):
    """Comprehensive evaluation emitted by Evaluator to student and Coordinator."""
    grades: List[Grade] = Field(..., description="Grade item for each question")
    overall_feedback: str = Field(..., description="Summary feedback covering strengths and weaknesses")
    weak_concepts: List[str] = Field(default_factory=list, description="Concepts scoring < 2 needing re-teaching")
    mastery_summary: str = Field(default="", description="Encouraging closing remark or milestone message")
